### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by henry40408** [henry40408/awesome-stars#6]
### TODO List

- [x] Implement all features in 1.x
  - [x] Use GitHub token
  - [x] Attach star tags on repository page
